NETWAYS/ansible-collection-icinga

- molecule/default/prepare.yml
> Replace `package` with `apt`

- .github/workflows/molecule.yml
- plugins/action/icinga2_object.py
- plugins/module_utils/parse.py
- plugins/modules/icinga2_idomysqlconnection.py
- plugins/modules/icinga2_idopgsqlconnection.py
- roles/icinga2/tasks/features.yml
- roles/icinga2/tasks/features/idomysql.yml
- roles/icinga2/tasks/features/idopgsql.yml
Examples for those cases at the moment:
* RHEL 7+8 with Ansible
fixes #49
> Improve compatibility for Ansible 2.9 and Python 3.6

- plugins/action/icinga2_object.py
- plugins/modules/icinga2_apilistener.py
- plugins/modules/icinga2_apiuser.py
- plugins/modules/icinga2_checkcommand.py
- plugins/modules/icinga2_checkercomponent.py
- plugins/modules/icinga2_endpoint.py
- plugins/modules/icinga2_filelogger.py
- plugins/modules/icinga2_graphitewriter.py
- plugins/modules/icinga2_host.py
- plugins/modules/icinga2_hostgroup.py
- plugins/modules/icinga2_icingaapplication.py
- plugins/modules/icinga2_idomysqlconnection.py
- plugins/modules/icinga2_idopgsqlconnection.py
- plugins/modules/icinga2_influxdbwriter.py
- plugins/modules/icinga2_notificationcomponent.py
- plugins/modules/icinga2_service.py
- plugins/modules/icinga2_servicegroup.py
- plugins/modules/icinga2_sysloglogger.py
- plugins/modules/icinga2_timeperiod.py
- plugins/modules/icinga2_zone.py
- roles/icinga2/tasks/configure.yml
- roles/icinga2/tasks/features/idomysql.yml
- roles/icinga2/tasks/features/idopgsql.yml
I'm not really happy with how the modules are implemented right now. But so far this will at least support check mode. Since the modules are not really actively doing anything.
fixes #50
> Fix check_mode

- doc/features/feature-ido.md
downtimehistory_age needs to be used instead of downtimehistory
> Wrong parameter

- plugins/modules/icinga2_influxdbwriter.py
Added the following attributes to the module:
```
ssl_insecure_noverify  = dict(type='bool'),
basic_auth             = dict(type='dict'),
```
ref #77
> Add new attributes to feature module InfluxDB

- roles/icinga2/vars/main.yml
> Add ConfigDir to the icinga2 reserved list

- doc/objects.md
> Add documentation snippet for CheckCommand

- plugins/action/icinga2_object.py
The PR checks if assign rules are given if the service should be a "apply" rule. 
Ref #87
> Check if assign and apply are set 

- roles/icinga2/tasks/configure.yml
Fragmentspath could be any length, need to count that before removing files
> fixed wrong count in fragmentspath

- molecule/default/converge.yml
- molecule/default/files/icinga2_command
- molecule/default/host_vars/icinga-default.yaml
- molecule/default/tests/integration/test_custom_file.py
- roles/icinga2/tasks/configure.yml
- roles/icinga2/tasks/objects.yml
* add custom config variable
* check if config is set before clearing old conf files
* prepare custom config paths in fragments temp dir 
* add test for custom config files
ref #30
> add custom config files

- README.md
- doc/role-icinga2.md
- doc/role-repos.md
> Added documentation for custom config

- roles/icinga2/defaults/main.yml
- roles/icinga2/tasks/configure.yml
- roles/icinga2/tasks/features/api.yml
- roles/icinga2/tasks/objects.yml
when custom config is empty the collection will fail, because of _icinga2_custom_conf_paths is undefined.
> fix empty custom config

- doc/role-icinga2/features.md
- doc/role-icinga2/features/feature-influxdb2.md
- doc/role-icinga2/features/feature-livestatus.md
- doc/role-icinga2/features/feature-perfdata.md
- plugins/modules/icinga2_livestatuslistener.py
- roles/icinga2/tasks/features/livestatus.yml
- roles/icinga2/vars/main.yml
> Add object and feature LiveStatusListener

- .github/workflows/python-test.yml
- .pylintrc
- Makefile
- plugins/action/icinga2_object.py
- plugins/filter/prefix.py
- plugins/lookup/icinga2_parser.py
- plugins/module_utils/parse.py
- plugins/modules/icinga2_elasticsearchwriter.py
- plugins/modules/icinga2_gelfwriter.py
- plugins/modules/icinga2_icingadb.py
- plugins/modules/icinga2_influxdb2writer.py
- plugins/modules/icinga2_opentsdbwriter.py
- plugins/modules/icinga2_perfdatawriter.py
Added pylint to CI Workflows
Fixes indent-errors in several files
> Add pylint to CI Workflows

- .github/workflows/build.yml
- roles/icinga2/tasks/features/api.yml
adds variable to set port for the Icinga 2 CA Host
fixes #113
> CA Host port should be manageable

- changelogs/fragments/fix_ca_host_filter.yml
- roles/icinga2/tasks/features/api.yml
> Fix sneaky bug in default filter for icinga2_ca_host

- plugins/modules/icinga2_idomysqlconnection.py
- plugins/modules/icinga2_idopgsqlconnection.py
- roles/icinga2/tasks/features/idomysql.yml
- roles/icinga2/tasks/features/idopgsql.yml
> Add TLS support to import schema for sql features

- .ansible-lint
- roles/icinga2/tasks/main.yml
- roles/monitoring_plugins/tasks/install_on_RedHat.yml
- roles/repos/tasks/main.yml
Change include path to absolute role path. 
```
paths:
- "{{ role_path }}/vars"
```
ref #148
> fix wrongly include of vars files

- doc/role-icinga2/objects.md
Adds documentation for templates.
fixes #156
> Add documentation for Icinga 2 templates

- changelogs/fragments/feature_add_satellite_delegation.yml
- doc/role-icinga2/features/feature-api.md
- roles/icinga2/tasks/features/api.yml
> Adds possibility to delegate ticket creation to satellites

- changelogs/fragments/fix_issue_228.yml
- roles/icinga2/tasks/objects.yml
Fixes #228, collect of icinga2_objects when icinga2_config_host is not defined
> Fix 228 collect of icinga2_objects

- roles/icingadb_redis/defaults/main.yml
- roles/icingadb_redis/templates/icingadb-redis.conf.j2
Add some options for tls to redis config template
> add tls options to redis

- .github/workflows/test_icingaweb2_ini_template.yml
- requirements-test-2.15.txt
- requirements-test-2.16.2.txt
- requirements-test-2.16.txt
- requirements-test-2.17.txt
Split up the tests for each version 
Removed old requirements file
ref #314
> Adjust ini_template_tests

- plugins/module_utils/parse.py
> Check if list is truthy before using it

- changelogs/fragments/doc_permissions_info.yml
- doc/getting-started.md
Regarding the issue #337, added some information about required permissions for run as root.
> Add info about root permissions for playbook

- changelogs/fragments/fix_issue_344_allow_loop_variable_usage.yml
- plugins/action/icinga2_object.py
- plugins/module_utils/parse.py
> Fix bug when using 'key' or 'value' variables

- changelogs/fragments/fix_issue_377.yml
- roles/icinga2/tasks/features/api.yml
Fixes https://github.com/NETWAYS/ansible-collection-icinga/issues/377
> 377: Fix Self signed certificate idempotency

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/382-fix-remote-certificates.yml
- changelogs/fragments/fix_issue_377.yml
- changelogs/fragments/fix_pr_379.yml
- galaxy.yml
Merge release 0.4.2 back into main.
> Release 0.4.2

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/feature_add_monitoring.yml
- changelogs/fragments/fix-260-complex-db-passwords.yml
- changelogs/fragments/fix-404-disabled-modules.yml
- changelogs/fragments/fix-missing-config-monitoring-module.yml
- changelogs/fragments/fix-runonce-serial.yml
- galaxy.yml
Merge release 0.4.3 back into main.
> Release 0.4.3
