README.md
We replace v0.1.0 (this tag does not exist on github) by 0.1.0 into the collection usage examples.
=> Use correct version number into examples

.github/workflows/build.yml, molecule/default/host_vars/icinga-default.yaml, roles/icinga2/tasks/objects.yml
icinga2_objects are currently only used when defined at hostvars. This is not always useable and confuses many people.
=> support icinga2_objects var outside of hostvars 

doc/role-icinga2/features/feature-api.md, roles/icinga2/defaults/main.yml, roles/icinga2/tasks/objects.yml
PR solves issue if fqdn is generated or unknown. fixes #107 
[skip ci]
=> Add icinga2_config_host var 

changelogs/fragments/fix_idempotence_el.yml, plugins/action/icinga2_object.py, roles/icinga2/tasks/configure.yml
- icinga_object initial state was directory, which clashed with an initial state: absent since the directories didn't exist yet
- The cleanup for empty config dirs needs to exclude the starting directory
Fixes #126
=> Fix non-idenpotence during feature disabling

.github/workflows/build.yml, molecule/default/molecule.yml, requirements-test-2.10.7.txt, requirements-test-2.11.8.txt, roles/repos/tasks/Debian.yml
Due to issues in centos7 and debian container, we only can use ubuntu2204 as build environment. Otherwise no service can be start successful.
=> Systemd issues with centos7 and debian container

roles/repos/defaults/main.yml, roles/repos/tasks/Debian.yml
The apt-key tool is deprecated and therefore the keys need to be manually managed. 
It is backwards compatible because you could manage them manually anyways. 
ref #133
=> Remove apt-key task

molecule/default/molecule.yml, roles/icinga2/tasks/features/api.yml
When certificates aren't created over Icinga 2 CLI, the certificate directory isn't created by default. 
This PR adds a task to ensure the directory exists with the right permissions.
=> Certificate directory missing

roles/repos/defaults/main.yml, roles/repos/tasks/RedHat.yml
This is just a minor rewrite of the current epel task.  
Now the `epel-release` package is used instead of 'manually' deploying a \*.repo file.  
This should close #151.
=> Change epel task to make use of the 'epel-release' package

changelogs/fragments/feature_add_suse_installation.yml, roles/icinga2/tasks/install_on_Suse.yml, roles/icinga2/vars/Suse.yml
For issue: #157 
Add Role Tasks and vars for SUSE
=> Add Roles tasks and vars SLES

roles/icingadb/tasks/manage_schema_mysql.yml
When managing the DB schema in HA setups (i.e. with two master hosts), the import would be done on each host object, failing for whichever host comes second. `run_once` fixes this.
=> Fixes error with importing DB schema twice in HA setups

roles/icingadb/templates/icingadb.ini.j2
This PR adds the same set of configurable features to the `redis` part of `icingadb`'s configuration file as is already available for the database connection. Docs will follow in a dedicated PR.
=> Adds TLS and client certificate options for Redis

roles/icinga2/tasks/features/idopgsql.yml, roles/icingaweb2/tasks/manage_icingaweb_config.yml, roles/icingaweb2/tasks/manage_icingaweb_pgsql_db.yml
I changed some things to make IcingaWeb2 working with Postgres.
If you wish, I can attach the originally produced errors.
=> Fix icingaweb2 postgres

roles/icinga2/tasks/features/idopgsql.yml
The generated connection string was not working without quotes.
```
fatal: [node-01.icinga.monitoring.test.company.com]: FAILED! => {"changed": true, "cmd": "PGPASSWORD=\"VerySecret\" psql host=postgres-01.icinga.monitoring.test.company.com port=5432 user=icinga dbname=icinga     -w -f /usr/share/icinga2-ido-pgsql/schema/pgsql.sql\n", "delta": "0:00:00.032079", "end": "2023-07-26 14:04:01.266753", "msg": "non-zero return code", "rc": 2, "start": "2023-07-26 14:04:01.234674", "stderr": "psql: warning: extra command-line argument \"user=icinga\" ignored\npsql: warning: extra command-line argument \"dbname=icinga\" ignored\npsql: error: connection to server at \"postgres-01.icinga.monitoring.test.company.com\" (10.202.144.71), port 5432 failed: FATAL:  no pg_hba.conf entry for host …
```
=> fix psql command

changelogs/fragments/trivial_192.yml, roles/icingadb_redis/defaults/main.yml
From the [Redis documentation](https://redis.io/docs/management/config-file/):
By default, if no "bind" configuration directive is specified, Redis listens for connections from all available network interfaces on the host machine.  It is possible to listen to just one or multiple selected interfaces using the "bind" configuration directive, followed by one or more IP addresses.  Each address can be prefixed by "-", which means that redis will not fail to start if the address is not available. Being not available only refers to addresses that does not correspond to any network interface. Addresses that are already in use will always fail, and unsupported protocols will always BE silently skipped.
=> Allow IPv6 address to not exist

changelogs/fragments/bugfixes_icingaweb2_preferences.yml, roles/icingaweb2/defaults/main.yml
According to the changelog of Icinga Web 2 a user was not allowed to set the preferences to be stored in ini format since 2.9 and forced to do the migration in 2.11.
This means this change will make preferences work for current installation of 2.11 and newer and only break versions prior to 2.9, anyone who had this setting in 2.9 or 2.10 has to run the migration described in the changelog and it is very likely it was run already to be compatible.
So I did try to avoid complexity by considering this as bug fix and not a breaking change and trying to avoid it.
=> icingaweb2: Adjust preferences settings to store preferences in database

doc/role-icingadb_redis/role-icingadb_redis.md, roles/icingadb_redis/defaults/main.yml, roles/icingadb_redis/templates/icingadb-redis.conf.j2
For now we added basic `requirepass` capabilities. We might want to look into other, more advanced available configuration options?
=> Adds password capabilities to icingadb-redis configuration

changelogs/fragments/fixed_typo_in_api_yml_file.yml, roles/icinga2/tasks/features/api.yml
I am currently using ansible-collection-icinga to programmatically provision icinga and came across this typo. Thought it would be helpful :)
=> Fixed typo in api.yml

changelogs/fragments/bugfix-monitoring-plugins-installation-removal-cycle.yml, roles/monitoring_plugins/tasks/install_on_Debian.yml, roles/monitoring_plugins/tasks/install_on_RedHat.yml
The role `monitoring_plugins` has an issue where it tries to subtract one list from the other using the `difference` filter but fails to do so.  
Actually, it currently tries to subtract a string from a list which results in the list entry (that should be removed) to remain in the list.
Thus, this can lead to a cycle where a package is installed in one task and immediately removed in the next one, completely breaking idempotency and not achieving the goal.
This PR correctly subtracts lists from lists and should resolve the issue.
=> Fix incorrect cycle of installation and removal

.github/workflows/build.yml
In addition to omitting certain branch names, I thought it might be an idea to run the molecule scenarios only when actual content of the roles or other internal logic has been submitted.
=> Adjusts actions so scenarios don't **always** run

changelogs/fragments/feature_add_x509_module_installation.yml, doc/role-icingaweb2/module-x509.md, roles/icingaweb2/tasks/main.yml, roles/icingaweb2/tasks/manage_mysql_imports.yml, roles/icingaweb2/tasks/modules/x509.yml, roles/icingaweb2/vars/main.yml
Adds x509 module, including configuration of SNIs and CAs. I also added some internal logic for restarting web module daemons at the very end of the Icingaweb2 installation, when (supposedly) all needed configuration is done. #197 will profit from this, too.
Fixes #186
=> add installation for x509 module

doc/getting-started.md, doc/role-icingadb/role-icingadb.md, doc/role-icingaweb2/role-icingaweb2.md
This is in reaction to #185 and adds information regarding database installation + configuration to the docs.
An example of installing and configuring needed databases using `geerlingguy.mysql` has been added to the getting started guide, too.
Fixes #185
=> Adds docs on database setup

doc/role-icingadb/role-icingadb.md
=> Updates documentation for IcingaDB schema management

roles/icinga2/tasks/features/api.yml
Currently ticket creation is broken because cn option has a trailing curly brace.
=> remove superfluous curly brace

changelogs/fragments/minor_change_adjust_vars_lookup.yml, roles/icingaweb2/tasks/modules/businessprocess.yml, roles/icingaweb2/tasks/modules/director.yml, roles/icingaweb2/tasks/modules/manage_module_config.yml, roles/icingaweb2/tasks/modules/x509.yml
Right now, many variable lookups happen in the form of `vars['some']['nested'][variable]['value']`.
This can be problematic when the variable itself is another jinja-templated expression, see also #226 
Instead, we should look up variables like this wherever possible:
`some.nested[variable].value`
This PR adjusts all lookups which don't explicitly check the variable's existence via `is defined` to the alternative syntax.
=> Adjusts variable lookups

roles/icingaweb2/tasks/manage_icingaweb_pgsql_db.yml
If the LANG variable is set to anything other than english, it might be that the output does not contain `(0 rows)`, but contains e.g. `(0 Zeilen)` instead (in a German settting).
Prefixing the psqslcmd with `LANG=C` makes sure the output is always english...
=> execute the pgsqlcmd with LANG=C to make sure the output is in english and we can match for '(0 rows)' in the next task

changelogs/fragments/fix_missing_quotes_delegate_ticket.yml, roles/icinga2/tasks/features/api.yml
Added missing quotes to ticket delegation. Currently, the ticket creation fails with the following error message:
```
TASK [icinga.icinga.icinga2 : delegate ticket request to master] ***********************************************************************************************************************************************************************************************************************************************************
changed: [host1.local -> host0.local] => {"changed": true, "cmd": "icinga2 pki ticket --cn \"host1.local --salt XXXXXXXX\"", "delta": "0:00:00.062976", "end": "2023-12-29 11:33:07.761888", "msg": "", "rc": 0, "start": "2023-12-29 11:33:07.698912", "stderr": "", "stderr_lines": [], "stdout": "fc043b935aacd292b742b0aaecd63e9055c16c95", "stdout_lines": …
```
=> added missing quotes to ticket delegation

changelogs/fragments/fix_change_order_of_module_tasks.yml, roles/icingaweb2/tasks/main.yml
This PR enables and disables modules before configuration. Normally modules get enabled and mostly configured after in the GUI. 
This should be the preferred way. 
fixes #225
=> Fix module configuration task order

changelogs/fragments/fix-173-changeable-dependency-repos.yml, doc/role-monitoring_plugins/role-monitoring_plugins.md, roles/monitoring_plugins/defaults/main.yml, roles/monitoring_plugins/tasks/install_on_RedHat.yml
In order to install some of the `nagios-plugins-...` packages either `crb` or `powertools` is needed.  
Currently the appropriate repository is temporarily enabled while installing.
The decision on whether to use `crb` or `powertools` is now sourced out to a new variable `icinga_monitoring_plugins_dependency_repos`.  
This in turn allows for the user to overwrite that variable to temporarily allow for any repository to be enabled.
If `crb` / `powertools` do not suffice, the user can *'manually'* set the variable to something like this:
```yaml
icinga_monitoring_plugins_dependency_repos:
- "repo1"
- "repo2"
...
```
Alternatively it can be specified as
```yaml
icinga_monitoring_plugins_dependency_repos: "*"
```
to temporarily enable every known repository.
This fixes #173
=> Add variable for dependency repositories within monitoring_plugins role

molecule/local-default-pgsql/converge.yml, roles/icingadb/tasks/manage_schema_pgsql.yml
This fixes the issue that if icingadb_database_host is set to localhost, no host parameter is set on the commandline. Because it assumes it is a local connection. Which is not true if port is used as well. 
Could be a breaking change!
Fixes #256
=> removed localhost condition as default

changelogs/fragments/fix_suse12_dep_missing.yml, roles/icinga2/tasks/install_on_Suse.yml, roles/icinga2/vars/Suse-12.yml
This is a PR which combines the PR #261 from @dh-roland and some reworking of the packages handling. 
Per default, the libboost_regex1_66_0 will be installed and if the variable ansible_distribution_major_version is 12 it will be the libboost_regex1_54_0.
@dh-roland can you verify if it works, somehow my suse vagrant environment isn't working properly. Would be good if you could test this PR.
=> Suse 12 missing libboost dependency. 

roles/icingaweb2/tasks/modules/x509.yml
In reference to [Issue 263](https://github.com/Icinga/ansible-collection-icinga/issues/263), I replaced all references of "vars['icingaweb2_modules']" with just "icingaweb2_modules" as the use of "vars" was causing any use of templated variables to pass the template as a literal string instead of evaluating it for the desired value.
=> issues/263 fixed references of "vars" to use "icingaweb2_modules"

roles/monitoring_plugins/tasks/install_on_RedHat.yml
This was a intial idea to reuse the role repos for enabling the epel release. But if included it will deactivate the release repos and if not set to false. It will enable the repos even if you just want the epel release. 
So I will remove it and will install epel-release instead. 
@donien can you give your thoughts if this is the right way? 
ref #270
=> Fix hardcoded variables on including role repos

roles/icinga2/tasks/configure.yml, roles/icinga2/tasks/objects.yml
Relying on the umask will break on systems which do not allow read for other, using a defined mode makes it independent from umask settings on the target system.
=> [icinga2] fix file permissions for objects

doc/role-icinga2/objects.md
The documentation is not tabbed correctly causing build failures
=> Not tabbed correctly, caused build to fail

changelogs/fragments/fix_update_ca_ssl_cert_documentation, doc/role-icinga2/features/feature-api.md
Fixes documentation.
The correct variable name for the certificate authority certificate is ssl_cacert (not ssl_ca), as per playbook output.
```
fatal: [myhostFQDN]: FAILED! => {
"assertion": "((icinga2_ssl_cacert is defined and icinga2_ssl_cert is defined and icinga2_ssl_key is defined) or (icinga2_ssl_cacert is undefined and icinga2_ssl_cert is undefined and icinga2_ssl_key is undefined and icinga2_ca_host is defined))",
```
vs
```
TASK [icinga.icinga.icinga2 : api feature cleanup arguments list] *****************************************************
ok: [myhostFQDN] => (item={'key': 'name', 'value': 'api'})
ok: [myhostFQDN] => (item={'key': 'accept_config', 'value': True})
ok: [myhostFQDN] => (item={'key': 'accept_commands', 'value': True})
ok: [myhostFQDN] => (item={'key': …
```
=> Fix ssl_cacert variable on configuration of icinga2 api feature with custom certificates

changelogs/fragments/fix_issue_298.yml, roles/icingadb_redis/tasks/install_on_debian.yml, roles/icingadb_redis/tasks/install_on_redhat.yml, roles/icingadb_redis/tasks/install_on_suse.yml, roles/icingadb_redis/templates/icingadb-redis.conf.j2
Icinga's packages no longer create /var/log/icingadb-redis/ since logging moved to the journal by default. If logging to a file is needed, the according directory has to be created beforehand.
Fixes #298
=> Add tasks to create icingadb-redis log directory

roles/icingaweb2/tasks/manage_icingaweb_pgsql_db.yml
The Icingaweb2 role had an incorrect naming for the handling of postgresql databases. This PR replaces the mention of IDO with icingaweb db, similar to the usage of mysql/mariadb databases.
=> replaced IDO schema with icingaweb db schema for the icingaweb role

changelogs/fragments/fix_issue_303_x509_mysql_import.yml, doc/role-icingaweb2/module-x509.md, roles/icingaweb2/tasks/manage_mysql_imports.yml, roles/icingaweb2/tasks/modules/x509.yml
Fixes the automatic import of the x509 database schema using mysql by changing the variable reference `schema_path` to `schema_path_mysql`.
Fixes #303
=> Fix mysql database import for module x509

changelogs/fragments/fix_issue_308.yml, roles/icinga2/tasks/objects.yml
The previous conditions did not suffice in determining whether vars['icinga2_objects'] was a list or not. Thus the variable was sometimes treated as a list even though it was a dictionary for example. This resulted in task failures.
This commit applies proper checks. Fixes #308.
=> Properly check if vars['icinga2_objects'] is list

changelogs/fragments/fix_issue_301.yml, molecule/ini-configuration-tests/tests/integration/test_ini_config.py, roles/icingaweb2/templates/ini_template.j2
Within Icinga Web's ini files double quotes are needed to encapsulate certain values. Changed single quotes to double quotes in template.
Fixes #301
=> Use double quotes instead of single quotes in ini

changelogs/fragments/fix_issue_302.yml, roles/icingadb/templates/icingadb.ini.j2
The value of `icingadb_database_tls_insecure` is meant to be used in the IcingaDB config template if the variable is defined. Prior to this change the condition checked against `icingadb_database_tls_insecure` while the used value was `icingadb_database_insecure`.
Both cases now refer to `icingadb_database_tls_insecure`.
Fixes #302
=> Use correct variable for insecure tls connection

changelogs/fragments/fix_292_icinga2_objects_documentation.yml, doc/role-icinga2/objects.md
Change the documentation to better explain the intended behaviour of the variable `icinga2_objects`.
Shows the difference between this variable as a host variable and as a play variable.
Since the (allowed) usage differes here, this is now also reflected in the documentation.
Fixes #292
=> Better reflect the usage of `icinga2_objects`

roles/icingaweb2/defaults/main.yml, roles/icingaweb2/tasks/main.yml
Add a boolean `icingaweb2_ignore_unknown_errors` to ignore modules provided in `icingaweb2_modules` which are unknown to this collection.
This way users can define modules within `icingaweb2_modules` and use other Ansible code referencing the same variable without this collection's icingaweb2 role failing.
Fixes #288
=> Add toggle to ignore unknown Icinga Web 2 modules

changelogs/fragments/fix_variable_expansion_breaks.yml, roles/icingaweb2/tasks/manage_icingaweb_config.yml, roles/icingaweb2/tasks/modules/businessprocess.yml, roles/icingaweb2/tasks/modules/director.yml, roles/icingaweb2/tasks/modules/monitoring.yml
Calling `vars['var']` is an explicit reference to the a play's `vars` key which makes defining those variables at host level impossible.
Also, when defining a variable in `vars` by providing a host variable the variable expansion breaks.
`vars` -> `key: "{{ host_variable_foo }}"` will be returned as a literal string when looked up via `vars['key']` without any expansion.
This commit fixes #291 by refering to just the variable name wherever suitable.
=> Fix bad variable expansion concerning vars['var']

doc/role-icingaweb2/role-icingaweb2.md
This adds some documentation regarding user and group authentication backends and how to use their respective variables.
Fixes #318
=> Add documentation for Icinga Web 2 authentication

changelogs/fragments/fix_327_unavailable_plugin.yml, roles/monitoring_plugins/tasks/main.yml
=> Fix bug where known but unavailable plugins would not be skipped

changelogs/fragments/feature_monitoring_plugins_suse.yml, doc/role-monitoring_plugins/check_command_list.md, doc/role-monitoring_plugins/role-monitoring_plugins.md, roles/monitoring_plugins/tasks/install_on_Suse.yml, roles/monitoring_plugins/vars/Suse.yml
This PR adds support for Suse in the role `monitoring_plugins`.
It will help to finish #259.
=> Add support for Suse in role 'monitoring_plugins'

roles/icingaweb2/handlers/main.yml, roles/icingaweb2/tasks/modules/director.yml
This adds handlers to the 'icingaweb2' role to take care of Icinga Director schema migrations and its kickstart. Running multiple roles in order should also run their handlers in order. This way the Icinga 2 API should be up and operational for the Director to use for kickstart.
Fixes #319
=> Add Director migration and kickstart handlers

changelogs/allow_mutiline_maged_string.yml, roles/icingadb/templates/icingadb.ini.j2, roles/icingadb_redis/templates/icingadb-redis.conf.j2
ansible_managed is allowed to be a multiline string.
the PR lets every line start with a "#".
=> allow multiline managed by ansible

changelogs/fragments/fix-port-var-name.yaml, roles/icinga2/tasks/features/api.yml
Fixes:
```yaml
fatal: [agent]: FAILED! => 
msg: 'Call to module failed: Unsupported parameters for (icinga2_apilistener) module:
ca_host_port. Supported parameters include: accept_commands, accept_config, access_control_allow_origin,
bind_host, bind_port, cipher_list, environment, file, max_anonymous_clients, name,
order, state, ticket_salt, tls_handshake_timeout, tls_protocolmin.'
```
Caused by using `ca_host_port`:
```yaml
icinga2_features:
- name: api
ca_host: '123.123.123.123'
ca_host_port: '443'
```
=> Fix icinga2_ca_host_port cleanup argument name

changelogs/fragments/fix_issue_309.yml, roles/icinga2/tasks/objects.yml
Using `icinga2_custom_config` allows deploying custom configuration files. They are read in from the `files` directory. This change allows for the use of nested directories instead of relying on just one directory level.
Fixes #309
=> Add ability to use nested directories for config

changelogs/fragments/feature_add_compatlogger.yml, doc/role-icinga2/features.md, doc/role-icinga2/features/feature-compatlog.md, doc/role-icinga2/objects.md, plugins/modules/icinga2_compatlogger.py, roles/icinga2/tasks/features/compatlog.yml, roles/icinga2/vars/main.yml
=> Add object and feature for CompatLogger

roles/icingaweb2/tasks/modules/manage_mysql_imports.yml
=> fix(icingaweb2): restore support for mysql on x509 module 

changelogs/fragments/fix_issue_285.yml, roles/icingaweb2/templates/ini_template.j2
Explicitly quote numeric values in 'ini_template.j2' to ensure compatibilty with certain versions of Jinja2.
Fixes #285
=> Fix template to properly quote numeric values

changelogs/fragments/fix_issue_367.yml, roles/icingaweb2/tasks/manage_icingaweb_config.yml
The port for Icinga Web's database connection is no properly set inside of 'resources.ini'.
Fixes #367
=> Add port to Icinga Web's own database connection

changelogs/fragments/fix_issue_371.yml, roles/icinga2/tasks/features/api.yml
The 'ticket_salt' in the API feature is now using the constant 'TicketSalt' as its value. This avoids accidental exposure as the actual secret is kept on a per host basis using constants. The default for the constant 'TicketSalt' is just an empty string if unchanged by the user.
Fixes #371
=> Fix exposure of TicketSalt on Satellites / Agents

changelogs/fragments/fix_issue_372.yml, plugins/filter/prefix.py
Testing for 'if type(var) is XY' is not sufficient anymore since the actual type can now be something like '_AnsibleLazyTemplateDict'.
Changed in favor of 'if isinstance(var, XY)'.
Fixes #372
=> Fix bug with current beta release of Ansible Core

changelogs/fragments/379-tls-auth-clients.yml, roles/icingadb/templates/icingadb.ini.j2, roles/icingadb_redis/defaults/main.yml, roles/icingadb_redis/templates/icingadb-redis.conf.j2
* Client certificate verification should be configurable to allow for more flexibility.
* If communication with Redis should happen exclusively over TLS, the icingadb_redis_port variable must be set to "0". However, doing so will result in a misconfiguration in the Icinga DB Redis section, as the Redis port will also be set to 0.
ref/NC/858268
=> Add setting for clients certificate

roles/icinga2/tasks/configure.yml, roles/icinga2/tasks/features.yml, roles/icinga2/tasks/features/api.yml, roles/icinga2/tasks/objects.yml, roles/icingaweb2/tasks/main.yml, roles/icingaweb2/tasks/manage_icingaweb_db.yml
Add some labels to loops to not print secrets when running Ansible without verbosity.
Some labels now also remove clutter from the output.
=> Add labels to loops

changelogs/fragments/fix_pr_379.yml, roles/icingadb/templates/icingadb.ini.j2, roles/icingadb_redis/templates/icingadb-redis.conf.j2
In this PR we fix the misconfiguration in icingadb role, icingadb hasn't the  "tls-port" flag. It should be placed in icingadb-redis configuration.
=> Fix redis/icingadb config

changelogs/fragments/386_duplicate_objects.yml, roles/icinga2/tasks/objects.yml
This deduplicates collected Icinga 2 objects before writing them to files in order to save some time during execution.
=> Deduplicate Icinga 2 objects before writing
